name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push user-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./backend/user-service
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service

    - name: Build & Push asset-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/asset-service ./backend/asset-service
        docker push ${{ secrets.DOCKER_USERNAME }}/asset-service

    - name: Build & Push data-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/data-service ./backend/data-service
        docker push ${{ secrets.DOCKER_USERNAME }}/data-service

    - name: Build & Push analytics-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/analytics-service ./backend/analytics-service
        docker push ${{ secrets.DOCKER_USERNAME }}/analytics-service

    - name: Build & Push maintenance-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/maintenance-service ./backend/maintenance-service
        docker push ${{ secrets.DOCKER_USERNAME }}/maintenance-service

    - name: Build & Push reporting-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reporting-service ./backend/reporting-service
        docker push ${{ secrets.DOCKER_USERNAME }}/reporting-service

    - name: Build & Push notification-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service ./backend/notification-service
        docker push ${{ secrets.DOCKER_USERNAME }}/notification-service
